/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiBadge {
        /**
          * Visual variant of the badge
          * @default 'neutral'
         */
        "variant": 'neutral' | 'positive' | 'warning';
    }
}
declare global {
    interface HTMLUiBadgeElement extends Components.UiBadge, HTMLStencilElement {
    }
    var HTMLUiBadgeElement: {
        prototype: HTMLUiBadgeElement;
        new (): HTMLUiBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "ui-badge": HTMLUiBadgeElement;
    }
}
declare namespace LocalJSX {
    interface UiBadge {
        /**
          * Visual variant of the badge
          * @default 'neutral'
         */
        "variant"?: 'neutral' | 'positive' | 'warning';
    }
    interface IntrinsicElements {
        "ui-badge": UiBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-badge": LocalJSX.UiBadge & JSXBase.HTMLAttributes<HTMLUiBadgeElement>;
        }
    }
}
